---
vault_version: "v2025.10.1"
vault_image_digest: "sha256:29f7f1f40b0874439a3e7a33e29a31d03840c9e81545dcc297f3a90b2fac31b6"
# Cross Compile Docker Helper Scripts v1.7.0
# We use the linux/amd64 platform shell scripts since there is no difference between the different platform scripts
# https://github.com/dfunkt/xx
xx_image_digest: "sha256:bf24a9a88ea76af4a8f505bff19e16f91e06a702098a6496f44a43a52882cbc4"
rust_version: 1.90.0 # Rust version to be used
debian_version: trixie # Debian release name to be used
alpine_version: "3.22" # Alpine version to be used
# For which platforms/architectures will we try to build images
platforms: ["linux/amd64", "linux/arm64", "linux/arm/v7", "linux/arm/v6"]
# Determine the build images per OS/Arch
build_stage_image:
  debian:
    image: "docker.io/library/rust:{{rust_version}}-slim-{{debian_version}}"
  alpine: &musl_build_config
    image: "build_${TARGETARCH}${TARGETVARIANT}"
    arch_image:
      amd64: "ghcr.io/blackdex/rust-musl:x86_64-musl-stable-{{rust_version}}"
      amd64v3: "ghcr.io/blackdex/rust-musl:x86_64-musl-stable-{{rust_version}}"
      arm64: "ghcr.io/blackdex/rust-musl:aarch64-musl-stable-{{rust_version}}"
      armv7: "ghcr.io/blackdex/rust-musl:armv7-musleabihf-stable-{{rust_version}}"
      armv6: "ghcr.io/blackdex/rust-musl:arm-musleabi-stable-{{rust_version}}"
  scratch: *musl_build_config
# The final image which will be used to distribute the container images
runtime_stage_image:
  debian: "docker.io/library/debian:{{debian_version}}-slim"
  alpine: "docker.io/library/alpine:{{alpine_version}}"
  scratch: "scratch"
